#!/bin/sh

#DEFINIR ANCHO Y NUMERO DE LINEAS
menu_alto_lineas=11
menu_ancho=220
#MEDIDAS DE MONITOR NO TOCAR
monitor_ancho=$(cat /tmp/resoluciones | awk 'NR==2 {print}')
monitor_alto=$(cat /tmp/resoluciones | awk 'NR==3 {print}')
#ALINEAR A LA DERECHA ARRIBA
#XX=$(( $monitor_ancho - $menu_ancho -5 ))
#YY=$(( 25 ))
#ALINEADO A LA IZQUIERA ARRIBA
XX=10
YY=50
#ALINEADO AL CENTRO
#menu_alto_pixeles=$(( $menu_alto_lineas * 10 ))
#menu_mitad_ancho=$(( $menu_ancho / 2 ))
#XX=$(( $monitor_ancho / 2 - $menu_mitad_ancho ))
#YY=$(( $monitor_alto / 2 - $menu_alto_pixeles ))

reload_bspwm="bspc wm -r;dunstify -i $HOME/.config/dunst/iconpng/arch.png BSPWMRC RECARGADO"
reload_sxhkd="pkill -USR1 -x sxhkd;dunstify -i $HOME/.config/dunst/iconpng/arch.png SXHKDRC RECARGADO"
reb="reboot"
shut="poweroff"
logout="killall panel;bspc quit"

cmds="\
    Bloquear                        	slock
  Cerrar Sesion                   	${logout}
  Recargar BSPwm                  	${reload_bspwm}
  Recargar Sxhkd                  	${reload_sxhkd}
   Reinciar PC                     	${reb}
   Apagar PC                       	${shut}"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu -w $menu_ancho -x $XX -y $YY)" || exit 1

action=$(echo "$cmds" | grep "^$choice	" | cut -d '	' -f2)

IFS=';' read -ra com <<< "$action"

for i in "${com[@]}"
do
$i
done
